package bitbucket_v2

type EventType string

const (
	EVENT_PUSHED        EventType = "pushed"
	EVENT_CREATE        EventType = "create"
	EVENT_COMMIT        EventType = "commit"
	EVENT_FORK          EventType = "fork"
	EVENT_MQ            EventType = "mq"
	EVENT_DELETE        EventType = "delete"
	EVENT_REPORT_ISSUE  EventType = "report_issue"
	EVENT_ISSUE_UPDATE  EventType = "issue_update"
	EVENT_ISSUE_COMMENT EventType = "issue_comment"
	EVENT_WIKI_UPDATED  EventType = "wiki_updated"
	EVENT_WIKI_CREATED  EventType = "wiki_created"
	EVENT_FILE_UPLOADED EventType = "file_uploaded"
	EVENT_STRIP         EventType = "strip"
	//EVENT_REPORT_ISSUE                EventType = "report_issue"
	EVENT_START_FOLLOW_REPO           EventType = "start_follow_repo"
	EVENT_STOP_FOLLOW_REPO            EventType = "stop_follow_repo"
	EVENT_START_FOLLOW_ISSUE          EventType = "start_follow_issue"
	EVENT_STOP_FOLLOW_ISSUE           EventType = "stop_follow_issue"
	EVENT_START_FOLLOW_USER           EventType = "start_follow_user"
	EVENT_STOP_FOLLOW_USER            EventType = "stop_follow_user"
	EVENT_PULLREQUEST_CREATED         EventType = "pullrequest_created"
	EVENT_PULLREQUEST_UPDATED         EventType = "pullrequest_updated"
	EVENT_PULLREQUEST_FULFILLED       EventType = "pullrequest_fulfilled"
	EVENT_PULLREQUEST_REJECTED        EventType = "pullrequest_rejected"
	EVENT_PULLREQUEST_SUPERSEDED      EventType = "pullrequest_superseded"
	EVENT_PULLREQUEST_COMMENT_CREATED EventType = "pullrequest_comment_created"
	EVENT_PULLREQUEST_COMMENT_UPDATED EventType = "pullrequest_comment_updated"
	EVENT_PULLREQUEST_COMMENT_DELETED EventType = "pullrequest_comment_deleted"
	EVENT_CSET_COMMENT_UPDATED        EventType = "cset_comment_updated"
	EVENT_CSET_COMMENT_DELETED        EventType = "cset_comment_deleted"
	EVENT_CSET_COMMENT_CREATED        EventType = "cset_comment_created"
	EVENT_PULLREQUEST_LIKE            EventType = "pullrequest_like"
	EVENT_PULLREQUEST_UNLIKE          EventType = "pullrequest_unlike"
	EVENT_CSET_LIKE                   EventType = "cset_like"
	EVENT_CSET_UNLIKE                 EventType = "cset_unlike"
	EVENT_TEAM_ACCESS_GAINED_ADMIN    EventType = "team_access_gained_admin"
	EVENT_TEAM_ACCESS_GAINED_COLLAB   EventType = "team_access_gained_collab"
	EVENT_TEAM_LOST_ACCESS            EventType = "team_lost_access"
	EVENT_TEAM_ACCESS_CHANGED_ADMIN   EventType = "team_access_changed_admin"
	EVENT_TEAM_ACCESS_CHANGED_COLLAB  EventType = "team_access_changed_collab"
)
